Pb 1398
portworx/px-backup-api pull request #101
Opened 2021-05-11 18:58 UTC by ram-infrac

**What this PR does / why we need it**:
Permission API support in role service

**Which issue(s) this PR fixes** (optional)
Closes # PB-1398

2021-05-13 16:31 UTC, adityadani approved these changes

2021-05-14 00:23 UTC, adityadani requested changes

2021-05-14 00:23 UTC, adityadani commented on pkg/apis/v1/api.proto
> +message RolePermissionResponse { map<string, bool> rules = 1; }
On a second thought returning a boolean is not extensible. What if in future we want to differentiate between Read and Write permissions? Can we instead change this to 
```suggestion
message Permission {
     FullAccess bool
     ViewAccess bool
}
message RolePermissionResponse { map<string, Permission> rules = 1; }
```
In this way later on we can split Full into even more sub permissions if we want to.

2021-05-14 13:04 UTC, ram-infrac commented on pkg/apis/v1/api.proto
> +message RolePermissionResponse { map<string, bool> rules = 1; }
user can either have full access/view access,
if we want to detailed out RolePermissionResponse, we should send response for each create/update/delete/list operation

2021-05-14 14:41 UTC, adityadani commented on pkg/apis/v1/api.proto
> +message RolePermissionResponse { map<string, bool> rules = 1; }
My point is if you have a `map<string, bool>` then it becomes hard to extend it.
Instead have a `map<string, struct{}>` so that the struct is extendable. Right now the struct can have a single boolean value like you have right now.

2021-05-14 15:01 UTC, ram-infrac commented on pkg/apis/v1/api.proto
> +message RolePermissionResponse { map<string, bool> rules = 1; }
make sense, will update it to `struct` thanks

2021-05-18 06:18 UTC, adityadani approved these changes

2021-05-18 06:18 UTC, merged