PB-1244: Adding ownership object replacing owner in Metadata structure
portworx/px-backup-api pull request #92
Opened 2021-04-11 08:23 UTC by prashanthpx

**What this PR does / why we need it**:
Adds ownership object to Metadata section relacing the exiting Ownership (a name)

**Which issue(s) this PR fixes** (optional)
PB-1244

**Special notes for your reviewer**:
This PR would not be pushed to master till other changes in px-backup are done, doing so will break px-backup when someone vendors top of master

2021-04-11 11:54 UTC, siva-portworx approved these changes

2021-04-11 11:54 UTC, siva-portworx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
Don't we need to have ownership field in metadata definition as well? So that it will be stored with each instance of object.

2021-04-11 15:45 UTC, prashanthpx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
Yes needed. Added it.

2021-04-12 05:01 UTC, siva-portworx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
Will it not affect serialization, if we change the existing field to of different type? I mean when we try read the old object with this new definition.

2021-04-12 05:06 UTC, adityadani requested changes

2021-04-12 05:06 UTC, adityadani commented on pkg/apis/v1/common.proto
> -    string owner = 3;
This will break backward compatibility. In general, when using protobufs one should not replace a field type/number.
We will have to keep the owner field and mark it as Deprecated and introduce a new Ownership field.

2021-04-12 05:06 UTC, adityadani commented on pkg/apis/v1/common.proto
> +// Ownership information for objects(eg: bakcup object, schedule object).
nit: backup

2021-04-12 05:06 UTC, adityadani commented on pkg/apis/v1/common.proto
> +    // The storage system uses the username taken from the security
nit: Backup uses the username taken taken from the token...

2021-04-12 05:14 UTC, prashanthpx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
This is something which we need to see how to handle in migrating existing objects to new ones which need discussion.   
Removing a field in higher proto is an issue. 
One option I was thinking of is having the current `owner` as is but add another `OwnerShip` message separately and not use the current one.  As we discuss, we might come up with different options.

2021-04-12 05:14 UTC, prashanthpx commented on pkg/apis/v1/common.proto
> -    string owner = 3;
Yes, this is the thinking I had which I wanted to discuss hence i didn't pus the PR to master.

2021-04-12 05:19 UTC, siva-portworx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
Actually remove a field is not an issue, unless, we try to use the same index in future. If we do not reuse remove field number, it should not cause any issue.

2021-04-12 05:56 UTC, prashanthpx commented on pkg/apis/v1/common.proto
> +    Ownership ownership = 3;
Yes, we need to use different indexing.

2021-04-12 16:52 UTC, adityadani approved these changes

2021-04-12 16:56 UTC, ram-infrac approved these changes

2021-04-12 17:06 UTC, merged